# Generated by Django 5.1 on 2024-09-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_dog_neutered_alter_dog_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='neutered',
        ),
    ]
